# Changes here will be overwritten by Copier
_commit: v0.5.0
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2026'
email: richard.abdill@sagebase.org
existing_license_file: ''
full_name: Richard Abdill
gh_action_docs_preview: true
gh_action_pypi: false
github_org: sagebio-ada
license: Apache-2.0
project_description: A repository containing data models for NAMHub curation
project_name: nam-hub-models
project_slug: namhub

